language: shell

os:
  - linux

addons:
  apt_packages:
    - lib32stdc++6

jobs:
  fast_finish: true
  allow_failures:
    - env: SOURCEMOD=1.9
    - env: SOURCEMOD=1.11

env:
  - SOURCEMOD=1.9
  - SOURCEMOD=1.10
  - SOURCEMOD=1.11

before_script:
  - wget "https://www.sourcemod.net/latest.php?version=$SOURCEMOD&os=linux" -O sourcemod-$SOURCEMOD-linux.tar.gz
  - tar -xzf sourcemod-$SOURCEMOD-linux.tar.gz
  - mv sourcemod/scripting/sbpp_discord.sp addons/sourcemod/scripting/
  - cd addons/sourcemod/scripting/
  - mkdir -p include/system2
  - wget https://raw.githubusercontent.com/sbpp/sourcebans-pp/v1.x/game/addons/sourcemod/scripting/include/sourcebanspp.inc -O include/sourcebanspp.inc
  - wget https://raw.githubusercontent.com/sbpp/sourcebans-pp/v1.x/game/addons/sourcemod/scripting/include/sourcecomms.inc -O include/sourcecomms.inc
  - wget https://raw.githubusercontent.com/dordnung/System2/master/sourcemod/scripting/include/system2.inc -O include/system2.inc
  - wget https://raw.githubusercontent.com/dordnung/System2/master/sourcemod/scripting/include/system2/request.inc -O include/system2/request.inc
  - wget https://raw.githubusercontent.com/dordnung/System2/master/sourcemod/scripting/include/system2/legacy.inc -O include/system2/legacy.inc
  - chmod +x spcomp

script:
  - ./spcomp sbpp_discord.sp -E -v0